name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        test-group: [1, 2]

    steps:
    - name: Git clone
      uses: actions/checkout@v3

    - name: Write the .env file
      run: |
          echo '${{ secrets.PLAYWRIGHT_ENV }}' | tr '\r' '\n' > .env

    - name: Debug Environment Variables
      run: cat .env

    - name: Load Environment Variables from .env
      run: export $(grep -v '^#' .env | xargs)

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Ensure screenshots directory exists
      run: mkdir -p ./screenshots

    - name: Generate Feature File
      run: node generateFeature.js
    
    - name: Run Cucumber Tests
      run: npx cucumber-js

    - name: Create test summary
      uses: test-summary/action@v2.0
      if: always()
      with:
        paths: reports/*.xml

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-screenshots
        path: ./screenshots
